### ISSUE TITLE
Custom URL Schemes do not work

### ISSUE THREAD

**Issue by dlemmermann** [shannah/jdeploy#67]
I added the scheme "tomato" to our application and tried to open the app via (on Mac):

"open tomato://customer/32423434"

I received the message:

No application knows how to open URL tomato://customer/166907972 (Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1489, _LSFunction=runEvaluator}).

**Comment by shannah** [comment]
Ah, yes.  The installer adds this piece.
So far I've been reluctant to modify the app bundle as part of the auto-update process since this wouldn't be possible if the app were signed.  Even though right now we aren't using codesign on the apps, I think it will be easier later when we do add support for app signing.
